/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export declare namespace MultiSigStorage {
  export type TransactionStruct = {
    destination: PromiseOrValue<string>;
    value: PromiseOrValue<BigNumberish>;
    data: PromiseOrValue<BytesLike>;
    executed: PromiseOrValue<boolean>;
    metadata: PromiseOrValue<BytesLike>;
  };

  export type TransactionStructOutput = [
    string,
    BigNumber,
    string,
    boolean,
    string
  ] & {
    destination: string;
    value: BigNumber;
    data: string;
    executed: boolean;
    metadata: string;
  };
}

export interface EndowmentMultiSigEmitterInterface extends utils.Interface {
  functions: {
    "addOwnersEndowment(uint256,address[])": FunctionFragment;
    "approvalsRequirementChangeEndowment(uint256,uint256)": FunctionFragment;
    "confirmEndowment(uint256,address,uint256)": FunctionFragment;
    "createMultisig(address,uint256,address,address[],uint256,bool)": FunctionFragment;
    "depositEndowment(uint256,address,uint256)": FunctionFragment;
    "executeEndowment(uint256,uint256)": FunctionFragment;
    "executeFailureEndowment(uint256,uint256)": FunctionFragment;
    "initEndowmentMultiSigEmitter(address)": FunctionFragment;
    "removeOwnersEndowment(uint256,address[])": FunctionFragment;
    "replaceOwnerEndowment(uint256,address,address)": FunctionFragment;
    "revokeEndowment(uint256,address,uint256)": FunctionFragment;
    "submitEndowment(uint256,uint256,(address,uint256,bytes,bool,bytes))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addOwnersEndowment"
      | "approvalsRequirementChangeEndowment"
      | "confirmEndowment"
      | "createMultisig"
      | "depositEndowment"
      | "executeEndowment"
      | "executeFailureEndowment"
      | "initEndowmentMultiSigEmitter"
      | "removeOwnersEndowment"
      | "replaceOwnerEndowment"
      | "revokeEndowment"
      | "submitEndowment"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addOwnersEndowment",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "approvalsRequirementChangeEndowment",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmEndowment",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createMultisig",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositEndowment",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeEndowment",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "executeFailureEndowment",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "initEndowmentMultiSigEmitter",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOwnersEndowment",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "replaceOwnerEndowment",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeEndowment",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEndowment",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      MultiSigStorage.TransactionStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addOwnersEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvalsRequirementChangeEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMultisig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeFailureEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initEndowmentMultiSigEmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOwnersEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replaceOwnerEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEndowment",
    data: BytesLike
  ): Result;

  events: {
    "EndowmentApprovalsRequirementChange(uint256,uint256)": EventFragment;
    "EndowmentConfirmation(uint256,address,uint256)": EventFragment;
    "EndowmentDeposit(uint256,address,uint256)": EventFragment;
    "EndowmentExecution(uint256,uint256)": EventFragment;
    "EndowmentExecutionFailure(uint256,uint256)": EventFragment;
    "EndowmentOwnerReplace(uint256,address,address)": EventFragment;
    "EndowmentOwnersAddition(uint256,address[])": EventFragment;
    "EndowmentOwnersRemoval(uint256,address[])": EventFragment;
    "EndowmentRevocation(uint256,address,uint256)": EventFragment;
    "EndowmentSubmission(uint256,uint256,tuple)": EventFragment;
    "MultisigCreated(address,uint256,address,address[],uint256,bool)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "EndowmentApprovalsRequirementChange"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentConfirmation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentExecution"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentExecutionFailure"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentOwnerReplace"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentOwnersAddition"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentOwnersRemoval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentRevocation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentSubmission"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MultisigCreated"): EventFragment;
}

export interface EndowmentApprovalsRequirementChangeEventObject {
  endowmentId: BigNumber;
  approvalsRequired: BigNumber;
}
export type EndowmentApprovalsRequirementChangeEvent = TypedEvent<
  [BigNumber, BigNumber],
  EndowmentApprovalsRequirementChangeEventObject
>;

export type EndowmentApprovalsRequirementChangeEventFilter =
  TypedEventFilter<EndowmentApprovalsRequirementChangeEvent>;

export interface EndowmentConfirmationEventObject {
  endowmentId: BigNumber;
  sender: string;
  transactionId: BigNumber;
}
export type EndowmentConfirmationEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  EndowmentConfirmationEventObject
>;

export type EndowmentConfirmationEventFilter =
  TypedEventFilter<EndowmentConfirmationEvent>;

export interface EndowmentDepositEventObject {
  endowmentId: BigNumber;
  sender: string;
  value: BigNumber;
}
export type EndowmentDepositEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  EndowmentDepositEventObject
>;

export type EndowmentDepositEventFilter =
  TypedEventFilter<EndowmentDepositEvent>;

export interface EndowmentExecutionEventObject {
  endowmentId: BigNumber;
  transactionId: BigNumber;
}
export type EndowmentExecutionEvent = TypedEvent<
  [BigNumber, BigNumber],
  EndowmentExecutionEventObject
>;

export type EndowmentExecutionEventFilter =
  TypedEventFilter<EndowmentExecutionEvent>;

export interface EndowmentExecutionFailureEventObject {
  endowmentId: BigNumber;
  transactionId: BigNumber;
}
export type EndowmentExecutionFailureEvent = TypedEvent<
  [BigNumber, BigNumber],
  EndowmentExecutionFailureEventObject
>;

export type EndowmentExecutionFailureEventFilter =
  TypedEventFilter<EndowmentExecutionFailureEvent>;

export interface EndowmentOwnerReplaceEventObject {
  endowmentId: BigNumber;
  currOwner: string;
  newOwner: string;
}
export type EndowmentOwnerReplaceEvent = TypedEvent<
  [BigNumber, string, string],
  EndowmentOwnerReplaceEventObject
>;

export type EndowmentOwnerReplaceEventFilter =
  TypedEventFilter<EndowmentOwnerReplaceEvent>;

export interface EndowmentOwnersAdditionEventObject {
  endowmentId: BigNumber;
  owners: string[];
}
export type EndowmentOwnersAdditionEvent = TypedEvent<
  [BigNumber, string[]],
  EndowmentOwnersAdditionEventObject
>;

export type EndowmentOwnersAdditionEventFilter =
  TypedEventFilter<EndowmentOwnersAdditionEvent>;

export interface EndowmentOwnersRemovalEventObject {
  endowmentId: BigNumber;
  owners: string[];
}
export type EndowmentOwnersRemovalEvent = TypedEvent<
  [BigNumber, string[]],
  EndowmentOwnersRemovalEventObject
>;

export type EndowmentOwnersRemovalEventFilter =
  TypedEventFilter<EndowmentOwnersRemovalEvent>;

export interface EndowmentRevocationEventObject {
  endowmentId: BigNumber;
  sender: string;
  transactionId: BigNumber;
}
export type EndowmentRevocationEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  EndowmentRevocationEventObject
>;

export type EndowmentRevocationEventFilter =
  TypedEventFilter<EndowmentRevocationEvent>;

export interface EndowmentSubmissionEventObject {
  endowmentId: BigNumber;
  transactionId: BigNumber;
  transaction: MultiSigStorage.TransactionStructOutput;
}
export type EndowmentSubmissionEvent = TypedEvent<
  [BigNumber, BigNumber, MultiSigStorage.TransactionStructOutput],
  EndowmentSubmissionEventObject
>;

export type EndowmentSubmissionEventFilter =
  TypedEventFilter<EndowmentSubmissionEvent>;

export interface MultisigCreatedEventObject {
  multisigAddress: string;
  endowmentId: BigNumber;
  emitter: string;
  owners: string[];
  required: BigNumber;
  requireExecution: boolean;
}
export type MultisigCreatedEvent = TypedEvent<
  [string, BigNumber, string, string[], BigNumber, boolean],
  MultisigCreatedEventObject
>;

export type MultisigCreatedEventFilter = TypedEventFilter<MultisigCreatedEvent>;

export interface EndowmentMultiSigEmitter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EndowmentMultiSigEmitterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addOwnersEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      owners: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    approvalsRequirementChangeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      approvalsRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    confirmEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createMultisig(
      multisigAddress: PromiseOrValue<string>,
      endowmentId: PromiseOrValue<BigNumberish>,
      emitter: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      required: PromiseOrValue<BigNumberish>,
      requireExecution: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    executeFailureEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initEndowmentMultiSigEmitter(
      _multisigFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeOwnersEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      owners: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    replaceOwnerEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      currOwner: PromiseOrValue<string>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      transaction: MultiSigStorage.TransactionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addOwnersEndowment(
    endowmentId: PromiseOrValue<BigNumberish>,
    owners: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  approvalsRequirementChangeEndowment(
    endowmentId: PromiseOrValue<BigNumberish>,
    approvalsRequired: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  confirmEndowment(
    endowmentId: PromiseOrValue<BigNumberish>,
    sender: PromiseOrValue<string>,
    transactionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createMultisig(
    multisigAddress: PromiseOrValue<string>,
    endowmentId: PromiseOrValue<BigNumberish>,
    emitter: PromiseOrValue<string>,
    owners: PromiseOrValue<string>[],
    required: PromiseOrValue<BigNumberish>,
    requireExecution: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositEndowment(
    endowmentId: PromiseOrValue<BigNumberish>,
    sender: PromiseOrValue<string>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeEndowment(
    endowmentId: PromiseOrValue<BigNumberish>,
    transactionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  executeFailureEndowment(
    endowmentId: PromiseOrValue<BigNumberish>,
    transactionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initEndowmentMultiSigEmitter(
    _multisigFactory: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeOwnersEndowment(
    endowmentId: PromiseOrValue<BigNumberish>,
    owners: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  replaceOwnerEndowment(
    endowmentId: PromiseOrValue<BigNumberish>,
    currOwner: PromiseOrValue<string>,
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeEndowment(
    endowmentId: PromiseOrValue<BigNumberish>,
    sender: PromiseOrValue<string>,
    transactionId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitEndowment(
    endowmentId: PromiseOrValue<BigNumberish>,
    transactionId: PromiseOrValue<BigNumberish>,
    transaction: MultiSigStorage.TransactionStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addOwnersEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      owners: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    approvalsRequirementChangeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      approvalsRequired: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    confirmEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createMultisig(
      multisigAddress: PromiseOrValue<string>,
      endowmentId: PromiseOrValue<BigNumberish>,
      emitter: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      required: PromiseOrValue<BigNumberish>,
      requireExecution: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    executeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    executeFailureEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    initEndowmentMultiSigEmitter(
      _multisigFactory: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeOwnersEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      owners: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    replaceOwnerEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      currOwner: PromiseOrValue<string>,
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    submitEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      transaction: MultiSigStorage.TransactionStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "EndowmentApprovalsRequirementChange(uint256,uint256)"(
      endowmentId?: null,
      approvalsRequired?: null
    ): EndowmentApprovalsRequirementChangeEventFilter;
    EndowmentApprovalsRequirementChange(
      endowmentId?: null,
      approvalsRequired?: null
    ): EndowmentApprovalsRequirementChangeEventFilter;

    "EndowmentConfirmation(uint256,address,uint256)"(
      endowmentId?: null,
      sender?: null,
      transactionId?: null
    ): EndowmentConfirmationEventFilter;
    EndowmentConfirmation(
      endowmentId?: null,
      sender?: null,
      transactionId?: null
    ): EndowmentConfirmationEventFilter;

    "EndowmentDeposit(uint256,address,uint256)"(
      endowmentId?: null,
      sender?: null,
      value?: null
    ): EndowmentDepositEventFilter;
    EndowmentDeposit(
      endowmentId?: null,
      sender?: null,
      value?: null
    ): EndowmentDepositEventFilter;

    "EndowmentExecution(uint256,uint256)"(
      endowmentId?: null,
      transactionId?: null
    ): EndowmentExecutionEventFilter;
    EndowmentExecution(
      endowmentId?: null,
      transactionId?: null
    ): EndowmentExecutionEventFilter;

    "EndowmentExecutionFailure(uint256,uint256)"(
      endowmentId?: null,
      transactionId?: null
    ): EndowmentExecutionFailureEventFilter;
    EndowmentExecutionFailure(
      endowmentId?: null,
      transactionId?: null
    ): EndowmentExecutionFailureEventFilter;

    "EndowmentOwnerReplace(uint256,address,address)"(
      endowmentId?: null,
      currOwner?: null,
      newOwner?: null
    ): EndowmentOwnerReplaceEventFilter;
    EndowmentOwnerReplace(
      endowmentId?: null,
      currOwner?: null,
      newOwner?: null
    ): EndowmentOwnerReplaceEventFilter;

    "EndowmentOwnersAddition(uint256,address[])"(
      endowmentId?: null,
      owners?: null
    ): EndowmentOwnersAdditionEventFilter;
    EndowmentOwnersAddition(
      endowmentId?: null,
      owners?: null
    ): EndowmentOwnersAdditionEventFilter;

    "EndowmentOwnersRemoval(uint256,address[])"(
      endowmentId?: null,
      owners?: null
    ): EndowmentOwnersRemovalEventFilter;
    EndowmentOwnersRemoval(
      endowmentId?: null,
      owners?: null
    ): EndowmentOwnersRemovalEventFilter;

    "EndowmentRevocation(uint256,address,uint256)"(
      endowmentId?: null,
      sender?: null,
      transactionId?: null
    ): EndowmentRevocationEventFilter;
    EndowmentRevocation(
      endowmentId?: null,
      sender?: null,
      transactionId?: null
    ): EndowmentRevocationEventFilter;

    "EndowmentSubmission(uint256,uint256,tuple)"(
      endowmentId?: null,
      transactionId?: null,
      transaction?: null
    ): EndowmentSubmissionEventFilter;
    EndowmentSubmission(
      endowmentId?: null,
      transactionId?: null,
      transaction?: null
    ): EndowmentSubmissionEventFilter;

    "MultisigCreated(address,uint256,address,address[],uint256,bool)"(
      multisigAddress?: null,
      endowmentId?: null,
      emitter?: null,
      owners?: null,
      required?: null,
      requireExecution?: null
    ): MultisigCreatedEventFilter;
    MultisigCreated(
      multisigAddress?: null,
      endowmentId?: null,
      emitter?: null,
      owners?: null,
      required?: null,
      requireExecution?: null
    ): MultisigCreatedEventFilter;
  };

  estimateGas: {
    addOwnersEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      owners: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    approvalsRequirementChangeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      approvalsRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    confirmEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createMultisig(
      multisigAddress: PromiseOrValue<string>,
      endowmentId: PromiseOrValue<BigNumberish>,
      emitter: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      required: PromiseOrValue<BigNumberish>,
      requireExecution: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    executeFailureEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initEndowmentMultiSigEmitter(
      _multisigFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeOwnersEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      owners: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    replaceOwnerEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      currOwner: PromiseOrValue<string>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      transaction: MultiSigStorage.TransactionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addOwnersEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      owners: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    approvalsRequirementChangeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      approvalsRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    confirmEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createMultisig(
      multisigAddress: PromiseOrValue<string>,
      endowmentId: PromiseOrValue<BigNumberish>,
      emitter: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      required: PromiseOrValue<BigNumberish>,
      requireExecution: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    executeFailureEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initEndowmentMultiSigEmitter(
      _multisigFactory: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeOwnersEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      owners: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    replaceOwnerEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      currOwner: PromiseOrValue<string>,
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      sender: PromiseOrValue<string>,
      transactionId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitEndowment(
      endowmentId: PromiseOrValue<BigNumberish>,
      transactionId: PromiseOrValue<BigNumberish>,
      transaction: MultiSigStorage.TransactionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
