/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type {interfaces};
import type * as lib from "./lib";
export type {lib};
import type * as registrarSol from "./registrar.sol";
export type {registrarSol};
export type {LocalRegistrar} from "./LocalRegistrar";
