nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  "@terra-money/wallet-provider@3.8.0":
    peerDependencies:
      "@terra-money/terra.js": ^3.0.0
  "@toruslabs/openlogin@*":
    dependencies:
      "@babel/runtime": "*"
  eslint-config-react-app@7.0.0:
    peerDependencies:
      "@babel/plugin-syntax-flow": ^7.14.5
      "@babel/plugin-transform-react-jsx": ^7.14.9
  react-dev-utils@12.0.0:
    peerDependencies:
      typescript: ">=2.7"
      webpack: ">=4"
  react-scripts@5.0.0:
    peerDependencies:
      "@babel/plugin-syntax-flow": ^7.14.5
      "@babel/plugin-transform-react-jsx": ^7.14.9
      autoprefixer: ^10.0.2
