nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.1.1.cjs
packageExtensions:
  "@terra-money/wallet-provider@2.3.0":
    dependencies:
      react-dom: "^17.0.0"

  "@terra-dev/readonly-wallet-modal@2.3.0":
    dependencies:
      react-is: ">= 16.8.0"

  "@terra-dev/walletconnect-qrcode-modal@2.3.0":
    dependencies:
      react-is: ">= 16.8.0"

  "@terra-dev/walletconnect@2.3.0":
    dependencies:
      react: "^17.0.0"
      react-dom: "^17.0.0"

  "recharts@2.1.6":
    dependencies:
      prop-types: "^15.6.0"

  "react-dev-utils@11.0.4":
    dependencies:
      typescript: " >= 2.7"
      webpack: ">= 4"
