nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.1.1.cjs
packageExtensions:
  "recharts@2.1.9":
    peerDependencies:
      prop-types: "^15.6.0"

  "react-dev-utils@11.0.4":
    peerDependencies:
      typescript: " >= 2.7"
      webpack: ">= 4"

  "@terra-money/wallet-provider@3.8.0":
    peerDependencies:
      "@terra-money/terra.js": ^3.0.0

  "@toruslabs/openlogin@*":
    dependencies:
      "@babel/runtime": "*"

  "@craco/craco@6.4.3":
    peerDependencies:
      "@types/node": "*"
      "ts-node": "*"
      "typescript": ">=2"
