nodeLinker: node-modules

packageExtensions:
  "@terra-money/wallet-provider@3.11.1":
    peerDependencies:
      "@terra-money/terra.js": ^3.1.6
  eslint-config-react-app@7.0.1:
    peerDependencies:
      "@babel/plugin-syntax-flow": ^7.14.5
      "@babel/plugin-transform-react-jsx": ^7.14.9
  react-scripts@5.0.1:
    peerDependencies:
      "@babel/plugin-syntax-flow": ^7.14.5
      "@babel/plugin-transform-react-jsx": ^7.14.9

  "@walletconnect/heartbeat@1.2.0":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"

  "@walletconnect/types@2.6.1":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"

  "@walletconnect/utils@2.6.1":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"

  "@web3auth/ethereum-provider@5.1.1":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"

  "@web3auth/modal@5.1.1":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"
      "@walletconnect/client": "~1.x"
      "@walletconnect/types": "~1.x"
      "react": "^18.x"
      "react-dom": "^18.x"

  "@web3auth/openlogin-adapter@5.1.1":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"

  "@web3auth/wallet-connect-v1-adapter@5.1.1":
    peerDependencies:
      "@types/node": "*"
      "typescript": ">=2.7"

  "@web3auth/base-plugin@5.1.0":
    peerDependencies:
      "@babel/runtime": "^7.x"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
