nodeLinker: node-modules

packageExtensions:
  "@terra-money/wallet-provider@3.11.1":
    peerDependencies:
      "@terra-money/terra.js": ^3.1.6

  "eth-block-tracker@4.4.3":
    peerDependencies:
      "@babel/core": "^7.0.0"

  "web3-provider-engine@16.0.1":
    peerDependencies:
      "@babel/core": "^7.0.0"

  "@walletconnect/web3-provider@1.8.0":
    peerDependencies:
      "@babel/core": "^7.0.0"

  "@nrwl/devkit@15.7.0":
    peerDependencies:
      "typescript": "^4"

  "@nrwl/js@15.7.0":
    peerDependencies:
      "nx": ">= 14.1 <= 16"
      "typescript": "^4"

  "@nrwl/linter@15.7.0":
    peerDependencies:
      "nx": ">= 14.1 <= 16"
      "typescript": "^4"

  "@nrwl/workspace@15.7.0":
    peerDependencies:
      "typescript": "^4"

  "@nrwl/react@15.7.0":
    peerDependencies:
      "nx": ">= 14.1 <= 16"
      "typescript": "^4"

  "@nrwl/webpack@15.7.0":
    peerDependencies:
      "nx": ">= 14.1 <= 16"
      "typescript": "^4"
      "@babel/core": "^7.12.0"
      "@types/node": "*"

  "@nrwl/jest@15.7.0":
    peerDependencies:
      "nx": ">= 14.1 <= 16"
      "typescript": "^4"

  "@nrwl/eslint-plugin-nx@15.7.0":
    peerDependencies:
      "nx": ">= 14.1 <= 16"
      "typescript": "^4"
      "eslint": "^8.0.0"

  "@nrwl/rollup@15.7.0":
    peerDependencies:
      "nx": ">= 14.1 <= 16"
      "typescript": "^4"
      "@babel/core": "^7.12.0"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
