nodeLinker: node-modules

packageExtensions:
  "@terra-money/wallet-provider@3.11.1":
    peerDependencies:
      "@terra-money/terra.js": ^3.1.6

  "eslint-config-react-app@7.0.1":
    peerDependencies:
      "@babel/plugin-syntax-flow": ^7.14.5
      "@babel/plugin-transform-react-jsx": ^7.14.9

  "react-scripts@5.0.1":
    peerDependencies:
      "@babel/plugin-syntax-flow": ^7.14.5
      "@babel/plugin-transform-react-jsx": ^7.14.9

  "react-dev-utils@12.0.1":
    peerDependencies:
      typescript: ">=2.7"
      webpack: ">=4"

  "dns-over-http-resolver@1.2.3":
    dependencies:
      "node-fetch": "*"

  "eth-block-tracker@4.4.3":
    dependencies:
      "@babel/core": "^7.0.0"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
