nodeLinker: node-modules

packageExtensions:
  "@terra-money/wallet-provider@3.11.1":
    peerDependencies:
      "@terra-money/terra.js": ^3.1.6

  "eth-block-tracker@4.4.3":
    peerDependencies:
      "@babel/core": "^7.0.0"

  "web3-provider-engine@16.0.1":
    peerDependencies:
      "@babel/core": "^7.0.0"

  "@walletconnect/web3-provider@1.8.0":
    peerDependencies:
      "@babel/core": "^7.0.0"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
