nodeLinker: node-modules

packageExtensions:
  "@terra-money/wallet-provider@3.11.1":
    peerDependencies:
      "@terra-money/terra.js": ^3.1.6
  eslint-config-react-app@7.0.1:
    peerDependencies:
      "@babel/plugin-syntax-flow": ^7.14.5
      "@babel/plugin-transform-react-jsx": ^7.14.9
  react-scripts@5.0.1:
    peerDependencies:
      "@babel/plugin-syntax-flow": ^7.14.5
      "@babel/plugin-transform-react-jsx": ^7.14.9

  "@web3auth/base-plugin@7.0.4":
    peerDependencies:
      "@babel/runtime": ^7.x

yarnPath: .yarn/releases/yarn-3.3.0.cjs
