/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from "./Interface";
export type { interface };
import type * as swappingSol from "./swapping.sol";
export type { swappingSol };
