/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {FunctionFragment, Result} from "@ethersproject/abi";
import type {Listener, Provider} from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface BancorBondingCurveInterface extends utils.Interface {
  functions: {
    "calculatePurchaseReturn(uint256,uint256,uint32,uint256)": FunctionFragment;
    "calculateSaleReturn(uint256,uint256,uint32,uint256)": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "calculatePurchaseReturn" | "calculateSaleReturn" | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculatePurchaseReturn",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSaleReturn",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "calculatePurchaseReturn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "calculateSaleReturn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {};
}

export interface BancorBondingCurve extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BancorBondingCurveInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    calculatePurchaseReturn(
      supply: PromiseOrValue<BigNumberish>,
      reservebalance: PromiseOrValue<BigNumberish>,
      reserveratio: PromiseOrValue<BigNumberish>,
      depositamount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateSaleReturn(
      supply: PromiseOrValue<BigNumberish>,
      reservebalance: PromiseOrValue<BigNumberish>,
      reserveratio: PromiseOrValue<BigNumberish>,
      sellamount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    version(overrides?: CallOverrides): Promise<[string]>;
  };

  calculatePurchaseReturn(
    supply: PromiseOrValue<BigNumberish>,
    reservebalance: PromiseOrValue<BigNumberish>,
    reserveratio: PromiseOrValue<BigNumberish>,
    depositamount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateSaleReturn(
    supply: PromiseOrValue<BigNumberish>,
    reservebalance: PromiseOrValue<BigNumberish>,
    reserveratio: PromiseOrValue<BigNumberish>,
    sellamount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    calculatePurchaseReturn(
      supply: PromiseOrValue<BigNumberish>,
      reservebalance: PromiseOrValue<BigNumberish>,
      reserveratio: PromiseOrValue<BigNumberish>,
      depositamount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateSaleReturn(
      supply: PromiseOrValue<BigNumberish>,
      reservebalance: PromiseOrValue<BigNumberish>,
      reserveratio: PromiseOrValue<BigNumberish>,
      sellamount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    calculatePurchaseReturn(
      supply: PromiseOrValue<BigNumberish>,
      reservebalance: PromiseOrValue<BigNumberish>,
      reserveratio: PromiseOrValue<BigNumberish>,
      depositamount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateSaleReturn(
      supply: PromiseOrValue<BigNumberish>,
      reservebalance: PromiseOrValue<BigNumberish>,
      reserveratio: PromiseOrValue<BigNumberish>,
      sellamount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    calculatePurchaseReturn(
      supply: PromiseOrValue<BigNumberish>,
      reservebalance: PromiseOrValue<BigNumberish>,
      reserveratio: PromiseOrValue<BigNumberish>,
      depositamount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateSaleReturn(
      supply: PromiseOrValue<BigNumberish>,
      reservebalance: PromiseOrValue<BigNumberish>,
      reserveratio: PromiseOrValue<BigNumberish>,
      sellamount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
