export enum chainIDs {
  //for multi-chain wallets, generalize as either mainnet or testnet only
  testnet = "testnet",
  mainnet = "mainnet",
  terra_test = "pisco-1",
  terra_main = "phoenix-1",
  terra_classic = "columbus-5",
  terra_local = "localterra",
  eth_rinkeby = "4",
  eth_kovan = "42",
  eth_ropsten = "3",
  eth_main = "1",
  bnb_main = "56",
  bnb_test = "97",
  btc_test = "1",
  sol_dev = "devnet",
  sol_main = "mainnet-beta",
  sol_test = "testnet",
  cosmos_3 = "cosmoshub-3",
  cosmos_4 = "cosmoshub-4",
  cosmos_test = "cosmoshub-testnet",
}
