export enum chainIDs {
  //for multi-chain wallets, generalize as either mainnet or testnet only
  gen_testnet = "testnet",
  gen_mainnet = "mainnet",
  testnet = "bombay-12",
  mainnet = "columbus-5",
  localterra = "localterra",
  eth_rinkeby = "4",
  eth_kovan = "42",
  eth_ropsten = "3",
  eth_main = "1",
  bnb_main = "56",
  bnb_test = "97",
  btc_test = "1",
  sol_dev = "devnet",
  sol_main = "mainnet-beta",
  sol_test = "testnet",
  cosmos_3 = "cosmoshub-3",
  cosmos_4 = "cosmoshub-4",
  cosmos_test = "cosmoshub-testnet",
}
