import {
  AiFillHeart,
  AiFillSecurityScan,
  AiFillYoutube,
  AiOutlineHeart,
  AiOutlineInfoCircle,
  AiOutlineMedium,
  AiOutlineMinusCircle,
  AiOutlinePlus,
  AiOutlineQuestionCircle,
  AiOutlineUpload,
} from "react-icons/ai";
import {
  BiCheck,
  BiChevronDown,
  BiChevronRight,
  BiGlobe,
  BiSave,
  BiSearchAlt2,
  BiSun,
} from "react-icons/bi";
import {
  BsCheckCircle,
  BsExclamationCircleFill,
  BsFilterLeft,
  BsHourglassSplit,
  BsTwitter,
} from "react-icons/bs";
import { CgUndo } from "react-icons/cg";
import {
  FaBitcoin,
  FaChurch,
  FaDiscord,
  FaDonate,
  FaExclamation,
  FaFacebook,
  FaHospital,
  FaInstagram,
  FaLinkedin,
  FaLinkedinIn,
  FaTelegramPlane,
  FaTiktok,
  FaUniversity,
  FaUserCircle,
} from "react-icons/fa";
import { FaFileCsv, FaMoneyBills } from "react-icons/fa6";
import { FiCreditCard, FiMenu, FiMoon } from "react-icons/fi";
import { GoDash, GoLinkExternal, GoSync } from "react-icons/go";
import { GrFacebookOption } from "react-icons/gr";
import { ImFilePicture } from "react-icons/im";
import { IoMdArrowBack, IoMdDownload, IoMdListBox } from "react-icons/io";
import {
  IoClose,
  IoCloseCircle,
  IoCrop,
  IoPeople,
  IoWalletSharp,
  IoWarning,
} from "react-icons/io5";
import { LiaChalkboardTeacherSolid } from "react-icons/lia";
import {
  MdCardGiftcard,
  MdDelete,
  MdOutlineAdminPanelSettings,
  MdOutlineArrowBackIosNew,
  MdOutlineContentCopy,
  MdOutlineEmail,
  MdOutlineFileDownload,
  MdOutlineFilterAlt,
  MdOutlineFolder,
  MdOutlineStickyNote2,
  MdOutlineUploadFile,
  MdSpaceDashboard,
  MdWidgets,
} from "react-icons/md";
import { PiPaypalLogo } from "react-icons/pi";
import {
  RiFundsBoxLine,
  RiMapPin2Line,
  RiMoneyDollarCircleFill,
} from "react-icons/ri";
import { RxMixerHorizontal } from "react-icons/rx";
import { SiHiveBlockchain } from "react-icons/si";
import { TiArrowUnsorted } from "react-icons/ti";
import { VscLoading, VscTriangleDown, VscTriangleUp } from "react-icons/vsc";

export const icons = {
  Advisor: LiaChalkboardTeacherSolid,
  AdminPanel: MdOutlineAdminPanelSettings,
  ArrowBack: IoMdArrowBack,
  ArrowDown: BiChevronDown,
  ArrowRight: BiChevronRight,
  Back: MdOutlineArrowBackIosNew,
  Bitcoin: FaBitcoin,
  Blockchain: SiHiveBlockchain,
  Charity: FaDonate,
  Check: BiCheck,
  CheckCircle: BsCheckCircle,
  CircleMinus: AiOutlineMinusCircle,
  Close: IoClose,
  CloseCircle: IoCloseCircle,
  Copy: MdOutlineContentCopy,
  CreditCard: FiCreditCard,
  Crop: IoCrop,
  Dash: GoDash,
  Dashboard: MdSpaceDashboard,
  Delete: MdDelete,
  Discord: FaDiscord,
  DollarCircle: RiMoneyDollarCircleFill,
  Down: VscTriangleDown,
  Email: MdOutlineEmail,
  Exclamation: FaExclamation,
  ExclamationCircleFill: BsExclamationCircleFill,
  ExternalLink: GoLinkExternal,
  Facebook: GrFacebookOption,
  FacebookCircle: FaFacebook,
  FatArrowDownload: IoMdDownload,
  FileCSV: FaFileCsv,
  FileDownload: MdOutlineFileDownload,
  FileUpload: MdOutlineUploadFile,
  Filter: MdOutlineFilterAlt,
  FilterLeft: BsFilterLeft,
  FilterMixer: RxMixerHorizontal,
  Folder: MdOutlineFolder,
  Stocks: RiFundsBoxLine,
  Giftcard: MdCardGiftcard,
  Globe: BiGlobe,
  HeartFill: AiFillHeart,
  HeartOutline: AiOutlineHeart,
  Hospital: FaHospital,
  HourglassSplit: BsHourglassSplit,
  Info: AiOutlineInfoCircle,
  Instagram: FaInstagram,
  Linkedin: FaLinkedin,
  LinkedinIn: FaLinkedinIn,
  ListBox: IoMdListBox,
  Loading: VscLoading,
  MapPin: RiMapPin2Line,
  Medium: AiOutlineMedium,
  Menu: FiMenu,
  Money: FaMoneyBills,
  Moon: FiMoon,
  Paypal: PiPaypalLogo,
  Picture: ImFilePicture,
  Plus: AiOutlinePlus,
  Question: AiOutlineQuestionCircle,
  ReligiousOrganization: FaChurch,
  Save: BiSave,
  Search: BiSearchAlt2,
  SecurityScan: AiFillSecurityScan,
  StickyNote: MdOutlineStickyNote2,
  Sun: BiSun,
  Sync: GoSync,
  Telegram: FaTelegramPlane,
  Tiktok: FaTiktok,
  Twitter: BsTwitter,
  Undo: CgUndo,
  University: FaUniversity,
  Unsorted: TiArrowUnsorted,
  Up: VscTriangleUp,
  Upload: AiOutlineUpload,
  User: FaUserCircle,
  Users: IoPeople,
  Wallet: IoWalletSharp,
  Warning: IoWarning,
  Widget: MdWidgets,
  Youtube: AiFillYoutube,
} as const;

export type IconType = keyof typeof icons;
