/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dummyAggregatorV3InstanceSol from "./DummyAggregatorV3Instance.sol";
export type { dummyAggregatorV3InstanceSol };
import type * as dummyWMaticSol from "./DummyWMatic.sol";
export type { dummyWMaticSol };
import type * as accounts from "./accounts";
export type { accounts };
export type { DummyERC165CompatibleContract } from "./DummyERC165CompatibleContract";
export type { DummyERC20 } from "./DummyERC20";
export type { DummyGasService } from "./DummyGasService";
export type { DummyGateway } from "./DummyGateway";
export type { DummyRouter } from "./DummyRouter";
export type { DummyStrategy } from "./DummyStrategy";
export type { DummySwapRouter } from "./DummySwapRouter";
export type { DummyUniswapV3Factory } from "./DummyUniswapV3Factory";
export type { DummyVault } from "./DummyVault";
