/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iindexFundSol from "./Iindex-fund.sol";
export { IndexFund__factory } from "./IndexFund__factory";
