/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface IAccountsAllowanceInterface extends utils.Interface {
  functions: {
    "manageAllowances(uint32,address,address,uint256)": FunctionFragment;
    "queryAllowance(uint32,address,address)": FunctionFragment;
    "spendAllowance(uint32,address,uint256,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "manageAllowances"
      | "queryAllowance"
      | "spendAllowance"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "manageAllowances",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "queryAllowance",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "spendAllowance",
    values: [BigNumberish, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "manageAllowances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spendAllowance",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IAccountsAllowance extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAccountsAllowanceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    manageAllowances(
      endowId: BigNumberish,
      spender: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    queryAllowance(
      endowId: BigNumberish,
      spender: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    spendAllowance(
      endowId: BigNumberish,
      token: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  manageAllowances(
    endowId: BigNumberish,
    spender: string,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  queryAllowance(
    endowId: BigNumberish,
    spender: string,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  spendAllowance(
    endowId: BigNumberish,
    token: string,
    amount: BigNumberish,
    recipient: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    manageAllowances(
      endowId: BigNumberish,
      spender: string,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    queryAllowance(
      endowId: BigNumberish,
      spender: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    spendAllowance(
      endowId: BigNumberish,
      token: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    manageAllowances(
      endowId: BigNumberish,
      spender: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    queryAllowance(
      endowId: BigNumberish,
      spender: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    spendAllowance(
      endowId: BigNumberish,
      token: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    manageAllowances(
      endowId: BigNumberish,
      spender: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    queryAllowance(
      endowId: BigNumberish,
      spender: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    spendAllowance(
      endowId: BigNumberish,
      token: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
