/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export declare namespace IVault {
  export type VaultActionDataStruct = {
    destinationChain: string;
    strategyId: BytesLike;
    selector: BytesLike;
    accountIds: BigNumberish[];
    token: string;
    lockAmt: BigNumberish;
    liqAmt: BigNumberish;
    status: BigNumberish;
  };

  export type VaultActionDataStructOutput = [
    string,
    string,
    string,
    number[],
    string,
    BigNumber,
    BigNumber,
    number
  ] & {
    destinationChain: string;
    strategyId: string;
    selector: string;
    accountIds: number[];
    token: string;
    lockAmt: BigNumber;
    liqAmt: BigNumber;
    status: number;
  };
}

export declare namespace LibAccounts {
  export type BeneficiaryDataStruct = {
    endowId: BigNumberish;
    fundId: BigNumberish;
    addr: string;
  };

  export type BeneficiaryDataStructOutput = [number, BigNumber, string] & {
    endowId: number;
    fundId: BigNumber;
    addr: string;
  };

  export type BeneficiaryStruct = {
    data: LibAccounts.BeneficiaryDataStruct;
    enumData: BigNumberish;
  };

  export type BeneficiaryStructOutput = [
    LibAccounts.BeneficiaryDataStructOutput,
    number
  ] & { data: LibAccounts.BeneficiaryDataStructOutput; enumData: number };

  export type FeeSettingStruct = { payoutAddress: string; bps: BigNumberish };

  export type FeeSettingStructOutput = [string, BigNumber] & {
    payoutAddress: string;
    bps: BigNumber;
  };

  export type DelegateStruct = { addr: string; expires: BigNumberish };

  export type DelegateStructOutput = [string, BigNumber] & {
    addr: string;
    expires: BigNumber;
  };

  export type SettingsPermissionStruct = {
    locked: boolean;
    delegate: LibAccounts.DelegateStruct;
  };

  export type SettingsPermissionStructOutput = [
    boolean,
    LibAccounts.DelegateStructOutput
  ] & { locked: boolean; delegate: LibAccounts.DelegateStructOutput };

  export type SettingsControllerStruct = {
    acceptedTokens: LibAccounts.SettingsPermissionStruct;
    lockedInvestmentManagement: LibAccounts.SettingsPermissionStruct;
    liquidInvestmentManagement: LibAccounts.SettingsPermissionStruct;
    allowlistedBeneficiaries: LibAccounts.SettingsPermissionStruct;
    allowlistedContributors: LibAccounts.SettingsPermissionStruct;
    maturityAllowlist: LibAccounts.SettingsPermissionStruct;
    maturityTime: LibAccounts.SettingsPermissionStruct;
    earlyLockedWithdrawFee: LibAccounts.SettingsPermissionStruct;
    withdrawFee: LibAccounts.SettingsPermissionStruct;
    depositFee: LibAccounts.SettingsPermissionStruct;
    balanceFee: LibAccounts.SettingsPermissionStruct;
    name: LibAccounts.SettingsPermissionStruct;
    image: LibAccounts.SettingsPermissionStruct;
    logo: LibAccounts.SettingsPermissionStruct;
    sdgs: LibAccounts.SettingsPermissionStruct;
    splitToLiquid: LibAccounts.SettingsPermissionStruct;
    ignoreUserSplits: LibAccounts.SettingsPermissionStruct;
  };

  export type SettingsControllerStructOutput = [
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput,
    LibAccounts.SettingsPermissionStructOutput
  ] & {
    acceptedTokens: LibAccounts.SettingsPermissionStructOutput;
    lockedInvestmentManagement: LibAccounts.SettingsPermissionStructOutput;
    liquidInvestmentManagement: LibAccounts.SettingsPermissionStructOutput;
    allowlistedBeneficiaries: LibAccounts.SettingsPermissionStructOutput;
    allowlistedContributors: LibAccounts.SettingsPermissionStructOutput;
    maturityAllowlist: LibAccounts.SettingsPermissionStructOutput;
    maturityTime: LibAccounts.SettingsPermissionStructOutput;
    earlyLockedWithdrawFee: LibAccounts.SettingsPermissionStructOutput;
    withdrawFee: LibAccounts.SettingsPermissionStructOutput;
    depositFee: LibAccounts.SettingsPermissionStructOutput;
    balanceFee: LibAccounts.SettingsPermissionStructOutput;
    name: LibAccounts.SettingsPermissionStructOutput;
    image: LibAccounts.SettingsPermissionStructOutput;
    logo: LibAccounts.SettingsPermissionStructOutput;
    sdgs: LibAccounts.SettingsPermissionStructOutput;
    splitToLiquid: LibAccounts.SettingsPermissionStructOutput;
    ignoreUserSplits: LibAccounts.SettingsPermissionStructOutput;
  };

  export type SplitDetailsStruct = {
    max: BigNumberish;
    min: BigNumberish;
    defaultSplit: BigNumberish;
  };

  export type SplitDetailsStructOutput = [BigNumber, BigNumber, BigNumber] & {
    max: BigNumber;
    min: BigNumber;
    defaultSplit: BigNumber;
  };
}

export declare namespace SubDaoLib {
  export type VeTypeDataStruct = {
    value: BigNumberish;
    scale: BigNumberish;
    slope: BigNumberish;
    power: BigNumberish;
  };

  export type VeTypeDataStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    value: BigNumber;
    scale: BigNumber;
    slope: BigNumber;
    power: BigNumber;
  };

  export type VeTypeStruct = {
    ve_type: BigNumberish;
    data: SubDaoLib.VeTypeDataStruct;
  };

  export type VeTypeStructOutput = [
    number,
    SubDaoLib.VeTypeDataStructOutput
  ] & { ve_type: number; data: SubDaoLib.VeTypeDataStructOutput };

  export type DaoTokenDataStruct = {
    existingData: string;
    newInitialSupply: BigNumberish;
    newName: string;
    newSymbol: string;
    veBondingType: SubDaoLib.VeTypeStruct;
    veBondingName: string;
    veBondingSymbol: string;
    veBondingDecimals: BigNumberish;
    veBondingReserveDenom: string;
    veBondingReserveDecimals: BigNumberish;
    veBondingPeriod: BigNumberish;
  };

  export type DaoTokenDataStructOutput = [
    string,
    BigNumber,
    string,
    string,
    SubDaoLib.VeTypeStructOutput,
    string,
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber
  ] & {
    existingData: string;
    newInitialSupply: BigNumber;
    newName: string;
    newSymbol: string;
    veBondingType: SubDaoLib.VeTypeStructOutput;
    veBondingName: string;
    veBondingSymbol: string;
    veBondingDecimals: BigNumber;
    veBondingReserveDenom: string;
    veBondingReserveDecimals: BigNumber;
    veBondingPeriod: BigNumber;
  };

  export type DaoTokenStruct = {
    token: BigNumberish;
    data: SubDaoLib.DaoTokenDataStruct;
  };

  export type DaoTokenStructOutput = [
    number,
    SubDaoLib.DaoTokenDataStructOutput
  ] & { token: number; data: SubDaoLib.DaoTokenDataStructOutput };

  export type DaoSetupStruct = {
    quorum: BigNumberish;
    threshold: BigNumberish;
    votingPeriod: BigNumberish;
    timelockPeriod: BigNumberish;
    expirationPeriod: BigNumberish;
    proposalDeposit: BigNumberish;
    snapshotPeriod: BigNumberish;
    token: SubDaoLib.DaoTokenStruct;
  };

  export type DaoSetupStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    SubDaoLib.DaoTokenStructOutput
  ] & {
    quorum: BigNumber;
    threshold: BigNumber;
    votingPeriod: BigNumber;
    timelockPeriod: BigNumber;
    expirationPeriod: BigNumber;
    proposalDeposit: BigNumber;
    snapshotPeriod: BigNumber;
    token: SubDaoLib.DaoTokenStructOutput;
  };
}

export declare namespace SubDaoMessages {
  export type InstantiateMsgStruct = {
    id: BigNumberish;
    owner: string;
    quorum: BigNumberish;
    threshold: BigNumberish;
    votingPeriod: BigNumberish;
    timelockPeriod: BigNumberish;
    expirationPeriod: BigNumberish;
    proposalDeposit: BigNumberish;
    snapshotPeriod: BigNumberish;
    token: SubDaoLib.DaoTokenStruct;
    endowType: BigNumberish;
    endowOwner: string;
    registrarContract: string;
  };

  export type InstantiateMsgStructOutput = [
    number,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    SubDaoLib.DaoTokenStructOutput,
    number,
    string,
    string
  ] & {
    id: number;
    owner: string;
    quorum: BigNumber;
    threshold: BigNumber;
    votingPeriod: BigNumber;
    timelockPeriod: BigNumber;
    expirationPeriod: BigNumber;
    proposalDeposit: BigNumber;
    snapshotPeriod: BigNumber;
    token: SubDaoLib.DaoTokenStructOutput;
    endowType: number;
    endowOwner: string;
    registrarContract: string;
  };
}

export declare namespace AccountMessages {
  export type CreateEndowmentRequestStruct = {
    withdrawBeforeMaturity: boolean;
    maturityTime: BigNumberish;
    name: string;
    sdgs: BigNumberish[];
    tier: BigNumberish;
    endowType: BigNumberish;
    logo: string;
    image: string;
    members: string[];
    threshold: BigNumberish;
    duration: BigNumberish;
    allowlistedBeneficiaries: string[];
    allowlistedContributors: string[];
    earlyLockedWithdrawFee: LibAccounts.FeeSettingStruct;
    withdrawFee: LibAccounts.FeeSettingStruct;
    depositFee: LibAccounts.FeeSettingStruct;
    balanceFee: LibAccounts.FeeSettingStruct;
    proposalLink: BigNumberish;
    settingsController: LibAccounts.SettingsControllerStruct;
    parent: BigNumberish;
    maturityAllowlist: string[];
    ignoreUserSplits: boolean;
    splitToLiquid: LibAccounts.SplitDetailsStruct;
    referralId: BigNumberish;
  };

  export type CreateEndowmentRequestStructOutput = [
    boolean,
    BigNumber,
    string,
    BigNumber[],
    number,
    number,
    string,
    string,
    string[],
    BigNumber,
    BigNumber,
    string[],
    string[],
    LibAccounts.FeeSettingStructOutput,
    LibAccounts.FeeSettingStructOutput,
    LibAccounts.FeeSettingStructOutput,
    LibAccounts.FeeSettingStructOutput,
    BigNumber,
    LibAccounts.SettingsControllerStructOutput,
    number,
    string[],
    boolean,
    LibAccounts.SplitDetailsStructOutput,
    BigNumber
  ] & {
    withdrawBeforeMaturity: boolean;
    maturityTime: BigNumber;
    name: string;
    sdgs: BigNumber[];
    tier: number;
    endowType: number;
    logo: string;
    image: string;
    members: string[];
    threshold: BigNumber;
    duration: BigNumber;
    allowlistedBeneficiaries: string[];
    allowlistedContributors: string[];
    earlyLockedWithdrawFee: LibAccounts.FeeSettingStructOutput;
    withdrawFee: LibAccounts.FeeSettingStructOutput;
    depositFee: LibAccounts.FeeSettingStructOutput;
    balanceFee: LibAccounts.FeeSettingStructOutput;
    proposalLink: BigNumber;
    settingsController: LibAccounts.SettingsControllerStructOutput;
    parent: number;
    maturityAllowlist: string[];
    ignoreUserSplits: boolean;
    splitToLiquid: LibAccounts.SplitDetailsStructOutput;
    referralId: BigNumber;
  };

  export type DepositRequestStruct = {
    id: BigNumberish;
    lockedPercentage: BigNumberish;
    liquidPercentage: BigNumberish;
    donationMatch: string;
  };

  export type DepositRequestStructOutput = [
    number,
    BigNumber,
    BigNumber,
    string
  ] & {
    id: number;
    lockedPercentage: BigNumber;
    liquidPercentage: BigNumber;
    donationMatch: string;
  };

  export type ConfigResponseStruct = {
    owner: string;
    version: string;
    networkName: string;
    registrarContract: string;
    nextAccountId: BigNumberish;
  };

  export type ConfigResponseStructOutput = [
    string,
    string,
    string,
    string,
    BigNumber
  ] & {
    owner: string;
    version: string;
    networkName: string;
    registrarContract: string;
    nextAccountId: BigNumber;
  };

  export type StateResponseStruct = {
    closingEndowment: boolean;
    closingBeneficiary: LibAccounts.BeneficiaryStruct;
  };

  export type StateResponseStructOutput = [
    boolean,
    LibAccounts.BeneficiaryStructOutput
  ] & {
    closingEndowment: boolean;
    closingBeneficiary: LibAccounts.BeneficiaryStructOutput;
  };

  export type DonationMatchDataStruct = {
    reserveToken: string;
    uniswapFactory: string;
    poolFee: BigNumberish;
  };

  export type DonationMatchDataStructOutput = [string, string, number] & {
    reserveToken: string;
    uniswapFactory: string;
    poolFee: number;
  };

  export type DonationMatchStruct = {
    enumData: BigNumberish;
    data: AccountMessages.DonationMatchDataStruct;
  };

  export type DonationMatchStructOutput = [
    number,
    AccountMessages.DonationMatchDataStructOutput
  ] & { enumData: number; data: AccountMessages.DonationMatchDataStructOutput };

  export type InvestRequestStruct = {
    strategy: BytesLike;
    token: string;
    lockAmt: BigNumberish;
    liquidAmt: BigNumberish;
    gasFee: BigNumberish;
  };

  export type InvestRequestStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    strategy: string;
    token: string;
    lockAmt: BigNumber;
    liquidAmt: BigNumber;
    gasFee: BigNumber;
  };

  export type RedeemRequestStruct = {
    strategy: BytesLike;
    token: string;
    lockAmt: BigNumberish;
    liquidAmt: BigNumberish;
    gasFee: BigNumberish;
  };

  export type RedeemRequestStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    strategy: string;
    token: string;
    lockAmt: BigNumber;
    liquidAmt: BigNumber;
    gasFee: BigNumber;
  };

  export type RedeemAllRequestStruct = {
    strategy: BytesLike;
    token: string;
    redeemLocked: boolean;
    redeemLiquid: boolean;
    gasFee: BigNumberish;
  };

  export type RedeemAllRequestStructOutput = [
    string,
    string,
    boolean,
    boolean,
    BigNumber
  ] & {
    strategy: string;
    token: string;
    redeemLocked: boolean;
    redeemLiquid: boolean;
    gasFee: BigNumber;
  };

  export type UpdateEndowmentControllerRequestStruct = {
    id: BigNumberish;
    settingsController: LibAccounts.SettingsControllerStruct;
  };

  export type UpdateEndowmentControllerRequestStructOutput = [
    number,
    LibAccounts.SettingsControllerStructOutput
  ] & {
    id: number;
    settingsController: LibAccounts.SettingsControllerStructOutput;
  };

  export type UpdateEndowmentDetailsRequestStruct = {
    id: BigNumberish;
    owner: string;
    name: string;
    sdgs: BigNumberish[];
    logo: string;
    image: string;
    rebalance: LocalRegistrarLib.RebalanceParamsStruct;
  };

  export type UpdateEndowmentDetailsRequestStructOutput = [
    number,
    string,
    string,
    BigNumber[],
    string,
    string,
    LocalRegistrarLib.RebalanceParamsStructOutput
  ] & {
    id: number;
    owner: string;
    name: string;
    sdgs: BigNumber[];
    logo: string;
    image: string;
    rebalance: LocalRegistrarLib.RebalanceParamsStructOutput;
  };

  export type UpdateEndowmentSettingsRequestStruct = {
    id: BigNumberish;
    donationMatchActive: boolean;
    maturityTime: BigNumberish;
    allowlistedBeneficiaries: string[];
    allowlistedContributors: string[];
    maturity_allowlist_add: string[];
    maturity_allowlist_remove: string[];
    splitToLiquid: LibAccounts.SplitDetailsStruct;
    ignoreUserSplits: boolean;
  };

  export type UpdateEndowmentSettingsRequestStructOutput = [
    number,
    boolean,
    BigNumber,
    string[],
    string[],
    string[],
    string[],
    LibAccounts.SplitDetailsStructOutput,
    boolean
  ] & {
    id: number;
    donationMatchActive: boolean;
    maturityTime: BigNumber;
    allowlistedBeneficiaries: string[];
    allowlistedContributors: string[];
    maturity_allowlist_add: string[];
    maturity_allowlist_remove: string[];
    splitToLiquid: LibAccounts.SplitDetailsStructOutput;
    ignoreUserSplits: boolean;
  };

  export type UpdateFeeSettingRequestStruct = {
    id: BigNumberish;
    earlyLockedWithdrawFee: LibAccounts.FeeSettingStruct;
    depositFee: LibAccounts.FeeSettingStruct;
    withdrawFee: LibAccounts.FeeSettingStruct;
    balanceFee: LibAccounts.FeeSettingStruct;
  };

  export type UpdateFeeSettingRequestStructOutput = [
    number,
    LibAccounts.FeeSettingStructOutput,
    LibAccounts.FeeSettingStructOutput,
    LibAccounts.FeeSettingStructOutput,
    LibAccounts.FeeSettingStructOutput
  ] & {
    id: number;
    earlyLockedWithdrawFee: LibAccounts.FeeSettingStructOutput;
    depositFee: LibAccounts.FeeSettingStructOutput;
    withdrawFee: LibAccounts.FeeSettingStructOutput;
    balanceFee: LibAccounts.FeeSettingStructOutput;
  };
}

export declare namespace LocalRegistrarLib {
  export type RebalanceParamsStruct = {
    rebalanceLiquidProfits: boolean;
    lockedRebalanceToLiquid: BigNumberish;
    interestDistribution: BigNumberish;
    lockedPrincipleToLiquid: boolean;
    principleDistribution: BigNumberish;
    basis: BigNumberish;
  };

  export type RebalanceParamsStructOutput = [
    boolean,
    number,
    number,
    boolean,
    number,
    number
  ] & {
    rebalanceLiquidProfits: boolean;
    lockedRebalanceToLiquid: number;
    interestDistribution: number;
    lockedPrincipleToLiquid: boolean;
    principleDistribution: number;
    basis: number;
  };
}

export declare namespace AccountStorage {
  export type EndowmentStruct = {
    owner: string;
    name: string;
    sdgs: BigNumberish[];
    tier: BigNumberish;
    endowType: BigNumberish;
    logo: string;
    image: string;
    maturityTime: BigNumberish;
    rebalance: LocalRegistrarLib.RebalanceParamsStruct;
    proposalLink: BigNumberish;
    multisig: string;
    dao: string;
    daoToken: string;
    donationMatchActive: boolean;
    donationMatchContract: string;
    allowlistedBeneficiaries: string[];
    allowlistedContributors: string[];
    maturityAllowlist: string[];
    earlyLockedWithdrawFee: LibAccounts.FeeSettingStruct;
    withdrawFee: LibAccounts.FeeSettingStruct;
    depositFee: LibAccounts.FeeSettingStruct;
    balanceFee: LibAccounts.FeeSettingStruct;
    settingsController: LibAccounts.SettingsControllerStruct;
    parent: BigNumberish;
    ignoreUserSplits: boolean;
    splitToLiquid: LibAccounts.SplitDetailsStruct;
    referralId: BigNumberish;
    gasFwd: string;
  };

  export type EndowmentStructOutput = [
    string,
    string,
    BigNumber[],
    number,
    number,
    string,
    string,
    BigNumber,
    LocalRegistrarLib.RebalanceParamsStructOutput,
    BigNumber,
    string,
    string,
    string,
    boolean,
    string,
    string[],
    string[],
    string[],
    LibAccounts.FeeSettingStructOutput,
    LibAccounts.FeeSettingStructOutput,
    LibAccounts.FeeSettingStructOutput,
    LibAccounts.FeeSettingStructOutput,
    LibAccounts.SettingsControllerStructOutput,
    number,
    boolean,
    LibAccounts.SplitDetailsStructOutput,
    BigNumber,
    string
  ] & {
    owner: string;
    name: string;
    sdgs: BigNumber[];
    tier: number;
    endowType: number;
    logo: string;
    image: string;
    maturityTime: BigNumber;
    rebalance: LocalRegistrarLib.RebalanceParamsStructOutput;
    proposalLink: BigNumber;
    multisig: string;
    dao: string;
    daoToken: string;
    donationMatchActive: boolean;
    donationMatchContract: string;
    allowlistedBeneficiaries: string[];
    allowlistedContributors: string[];
    maturityAllowlist: string[];
    earlyLockedWithdrawFee: LibAccounts.FeeSettingStructOutput;
    withdrawFee: LibAccounts.FeeSettingStructOutput;
    depositFee: LibAccounts.FeeSettingStructOutput;
    balanceFee: LibAccounts.FeeSettingStructOutput;
    settingsController: LibAccounts.SettingsControllerStructOutput;
    parent: number;
    ignoreUserSplits: boolean;
    splitToLiquid: LibAccounts.SplitDetailsStructOutput;
    referralId: BigNumber;
    gasFwd: string;
  };
}

export declare namespace IAccountsDepositWithdrawEndowments {
  export type TokenInfoStruct = { addr: string; amnt: BigNumberish };

  export type TokenInfoStructOutput = [string, BigNumber] & {
    addr: string;
    amnt: BigNumber;
  };
}

export interface IAccountsInterface extends utils.Interface {
  functions: {
    "addGas(uint32,uint8,address,uint256)": FunctionFragment;
    "closeEndowment(uint32,((uint32,uint256,address),uint8))": FunctionFragment;
    "createDaoContract((uint32,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,(uint8,(address,uint256,string,string,(uint8,(uint128,uint256,uint128,uint128)),string,string,uint256,address,uint256,uint256)),uint8,address,address))": FunctionFragment;
    "createEndowment((bool,uint256,string,uint256[],uint8,uint8,string,string,address[],uint256,uint256,address[],address[],(address,uint256),(address,uint256),(address,uint256),(address,uint256),uint256,((bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256))),uint32,address[],bool,(uint256,uint256,uint256),uint256))": FunctionFragment;
    "depositDonationMatchERC20(uint32,address,uint256)": FunctionFragment;
    "depositERC20((uint32,uint256,uint256,address),address,uint256)": FunctionFragment;
    "depositMatic((uint32,uint256,uint256,address))": FunctionFragment;
    "manageAllowances(uint32,address,address,uint256)": FunctionFragment;
    "queryAllowance(uint32,address,address)": FunctionFragment;
    "queryConfig()": FunctionFragment;
    "queryEndowmentDetails(uint32)": FunctionFragment;
    "queryState(uint32)": FunctionFragment;
    "queryTokenAmount(uint32,uint8,address)": FunctionFragment;
    "setupDao(uint32,(uint256,uint256,uint256,uint256,uint256,uint128,uint256,(uint8,(address,uint256,string,string,(uint8,(uint128,uint256,uint128,uint128)),string,string,uint256,address,uint256,uint256))))": FunctionFragment;
    "setupDonationMatch(uint32,(uint8,(address,address,uint24)))": FunctionFragment;
    "spendAllowance(uint32,address,uint256,address)": FunctionFragment;
    "strategyInvest(uint32,(bytes4,string,uint256,uint256,uint256))": FunctionFragment;
    "strategyRedeem(uint32,(bytes4,string,uint256,uint256,uint256))": FunctionFragment;
    "strategyRedeemAll(uint32,(bytes4,string,bool,bool,uint256))": FunctionFragment;
    "swapToken(uint32,uint8,address,uint256,address,uint256)": FunctionFragment;
    "sweepForClosure(uint32,address)": FunctionFragment;
    "sweepForEndowment(uint32,uint8,address)": FunctionFragment;
    "updateAcceptedToken(uint32,address,address,bool)": FunctionFragment;
    "updateConfig(address)": FunctionFragment;
    "updateDelegate(uint32,uint8,uint8,address,uint256)": FunctionFragment;
    "updateEndowmentController((uint32,((bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)),(bool,(address,uint256)))))": FunctionFragment;
    "updateEndowmentDetails((uint32,address,string,uint256[],string,string,(bool,uint32,uint32,bool,uint32,uint32)))": FunctionFragment;
    "updateEndowmentSettings((uint32,bool,uint256,address[],address[],address[],address[],(uint256,uint256,uint256),bool))": FunctionFragment;
    "updateFeeSettings((uint32,(address,uint256),(address,uint256),(address,uint256),(address,uint256)))": FunctionFragment;
    "updateOwner(address)": FunctionFragment;
    "withdraw(uint32,uint8,address,uint32,(address,uint256)[])": FunctionFragment;
    "withdrawDonationMatchERC20(uint32,address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addGas"
      | "closeEndowment"
      | "createDaoContract"
      | "createEndowment"
      | "depositDonationMatchERC20"
      | "depositERC20"
      | "depositMatic"
      | "manageAllowances"
      | "queryAllowance"
      | "queryConfig"
      | "queryEndowmentDetails"
      | "queryState"
      | "queryTokenAmount"
      | "setupDao"
      | "setupDonationMatch"
      | "spendAllowance"
      | "strategyInvest"
      | "strategyRedeem"
      | "strategyRedeemAll"
      | "swapToken"
      | "sweepForClosure"
      | "sweepForEndowment"
      | "updateAcceptedToken"
      | "updateConfig"
      | "updateDelegate"
      | "updateEndowmentController"
      | "updateEndowmentDetails"
      | "updateEndowmentSettings"
      | "updateFeeSettings"
      | "updateOwner"
      | "withdraw"
      | "withdrawDonationMatchERC20"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addGas",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeEndowment",
    values: [BigNumberish, LibAccounts.BeneficiaryStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createDaoContract",
    values: [SubDaoMessages.InstantiateMsgStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createEndowment",
    values: [AccountMessages.CreateEndowmentRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "depositDonationMatchERC20",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC20",
    values: [AccountMessages.DepositRequestStruct, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositMatic",
    values: [AccountMessages.DepositRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "manageAllowances",
    values: [BigNumberish, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "queryAllowance",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "queryConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "queryEndowmentDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "queryState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "queryTokenAmount",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setupDao",
    values: [BigNumberish, SubDaoLib.DaoSetupStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setupDonationMatch",
    values: [BigNumberish, AccountMessages.DonationMatchStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "spendAllowance",
    values: [BigNumberish, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyInvest",
    values: [BigNumberish, AccountMessages.InvestRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyRedeem",
    values: [BigNumberish, AccountMessages.RedeemRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyRedeemAll",
    values: [BigNumberish, AccountMessages.RedeemAllRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapToken",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sweepForClosure",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sweepForEndowment",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAcceptedToken",
    values: [BigNumberish, string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateConfig",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDelegate",
    values: [BigNumberish, BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEndowmentController",
    values: [AccountMessages.UpdateEndowmentControllerRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEndowmentDetails",
    values: [AccountMessages.UpdateEndowmentDetailsRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEndowmentSettings",
    values: [AccountMessages.UpdateEndowmentSettingsRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeSettings",
    values: [AccountMessages.UpdateFeeSettingRequestStruct]
  ): string;
  encodeFunctionData(functionFragment: "updateOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      IAccountsDepositWithdrawEndowments.TokenInfoStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawDonationMatchERC20",
    values: [BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addGas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDaoContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositDonationMatchERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositMatic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manageAllowances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryEndowmentDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "queryState", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "queryTokenAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setupDao", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setupDonationMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spendAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategyInvest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategyRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategyRedeemAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sweepForClosure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sweepForEndowment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAcceptedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEndowmentController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEndowmentDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEndowmentSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDonationMatchERC20",
    data: BytesLike
  ): Result;

  events: {
    "AllowanceSpent(uint256,address,address,uint256)": EventFragment;
    "AllowanceUpdated(uint256,address,address,uint256,uint256,uint256)": EventFragment;
    "ConfigUpdated()": EventFragment;
    "DaoContractCreated(uint32,address)": EventFragment;
    "DonationDeposited(uint256,address,uint256)": EventFragment;
    "DonationMatchCreated(uint256,address)": EventFragment;
    "DonationWithdrawn(uint256,address,address,uint256)": EventFragment;
    "EndowmentClosed(uint256)": EventFragment;
    "EndowmentCreated(uint256,uint8)": EventFragment;
    "EndowmentDeposit(uint256,address,uint256,uint256)": EventFragment;
    "EndowmentInvested(uint8)": EventFragment;
    "EndowmentRedeemed(uint8)": EventFragment;
    "EndowmentSettingUpdated(uint256,string)": EventFragment;
    "EndowmentUpdated(uint256)": EventFragment;
    "EndowmentWithdraw(uint256,address,uint256,uint8,address,uint32)": EventFragment;
    "OwnerUpdated(address)": EventFragment;
    "RefundNeeded((string,bytes4,bytes4,uint32[],address,uint256,uint256,uint8))": EventFragment;
    "TokenSwapped(uint256,uint8,address,uint256,address,uint256)": EventFragment;
    "UnexpectedTokens((string,bytes4,bytes4,uint32[],address,uint256,uint256,uint8))": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AllowanceSpent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AllowanceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConfigUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DaoContractCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DonationDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DonationMatchCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DonationWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentClosed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentInvested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentRedeemed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentSettingUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EndowmentWithdraw"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RefundNeeded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenSwapped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnexpectedTokens"): EventFragment;
}

export interface AllowanceSpentEventObject {
  endowId: BigNumber;
  spender: string;
  tokenAddress: string;
  amount: BigNumber;
}
export type AllowanceSpentEvent = TypedEvent<
  [BigNumber, string, string, BigNumber],
  AllowanceSpentEventObject
>;

export type AllowanceSpentEventFilter = TypedEventFilter<AllowanceSpentEvent>;

export interface AllowanceUpdatedEventObject {
  endowId: BigNumber;
  spender: string;
  tokenAddress: string;
  newBalance: BigNumber;
  added: BigNumber;
  deducted: BigNumber;
}
export type AllowanceUpdatedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber, BigNumber],
  AllowanceUpdatedEventObject
>;

export type AllowanceUpdatedEventFilter =
  TypedEventFilter<AllowanceUpdatedEvent>;

export interface ConfigUpdatedEventObject {}
export type ConfigUpdatedEvent = TypedEvent<[], ConfigUpdatedEventObject>;

export type ConfigUpdatedEventFilter = TypedEventFilter<ConfigUpdatedEvent>;

export interface DaoContractCreatedEventObject {
  endowId: number;
  daoAddress: string;
}
export type DaoContractCreatedEvent = TypedEvent<
  [number, string],
  DaoContractCreatedEventObject
>;

export type DaoContractCreatedEventFilter =
  TypedEventFilter<DaoContractCreatedEvent>;

export interface DonationDepositedEventObject {
  endowId: BigNumber;
  tokenAddress: string;
  amount: BigNumber;
}
export type DonationDepositedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  DonationDepositedEventObject
>;

export type DonationDepositedEventFilter =
  TypedEventFilter<DonationDepositedEvent>;

export interface DonationMatchCreatedEventObject {
  endowId: BigNumber;
  donationMatchContract: string;
}
export type DonationMatchCreatedEvent = TypedEvent<
  [BigNumber, string],
  DonationMatchCreatedEventObject
>;

export type DonationMatchCreatedEventFilter =
  TypedEventFilter<DonationMatchCreatedEvent>;

export interface DonationWithdrawnEventObject {
  endowId: BigNumber;
  recipient: string;
  tokenAddress: string;
  amount: BigNumber;
}
export type DonationWithdrawnEvent = TypedEvent<
  [BigNumber, string, string, BigNumber],
  DonationWithdrawnEventObject
>;

export type DonationWithdrawnEventFilter =
  TypedEventFilter<DonationWithdrawnEvent>;

export interface EndowmentClosedEventObject {
  endowId: BigNumber;
}
export type EndowmentClosedEvent = TypedEvent<
  [BigNumber],
  EndowmentClosedEventObject
>;

export type EndowmentClosedEventFilter = TypedEventFilter<EndowmentClosedEvent>;

export interface EndowmentCreatedEventObject {
  endowId: BigNumber;
  endowType: number;
}
export type EndowmentCreatedEvent = TypedEvent<
  [BigNumber, number],
  EndowmentCreatedEventObject
>;

export type EndowmentCreatedEventFilter =
  TypedEventFilter<EndowmentCreatedEvent>;

export interface EndowmentDepositEventObject {
  endowId: BigNumber;
  tokenAddress: string;
  amountLocked: BigNumber;
  amountLiquid: BigNumber;
}
export type EndowmentDepositEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  EndowmentDepositEventObject
>;

export type EndowmentDepositEventFilter =
  TypedEventFilter<EndowmentDepositEvent>;

export interface EndowmentInvestedEventObject {
  arg0: number;
}
export type EndowmentInvestedEvent = TypedEvent<
  [number],
  EndowmentInvestedEventObject
>;

export type EndowmentInvestedEventFilter =
  TypedEventFilter<EndowmentInvestedEvent>;

export interface EndowmentRedeemedEventObject {
  arg0: number;
}
export type EndowmentRedeemedEvent = TypedEvent<
  [number],
  EndowmentRedeemedEventObject
>;

export type EndowmentRedeemedEventFilter =
  TypedEventFilter<EndowmentRedeemedEvent>;

export interface EndowmentSettingUpdatedEventObject {
  endowId: BigNumber;
  setting: string;
}
export type EndowmentSettingUpdatedEvent = TypedEvent<
  [BigNumber, string],
  EndowmentSettingUpdatedEventObject
>;

export type EndowmentSettingUpdatedEventFilter =
  TypedEventFilter<EndowmentSettingUpdatedEvent>;

export interface EndowmentUpdatedEventObject {
  endowId: BigNumber;
}
export type EndowmentUpdatedEvent = TypedEvent<
  [BigNumber],
  EndowmentUpdatedEventObject
>;

export type EndowmentUpdatedEventFilter =
  TypedEventFilter<EndowmentUpdatedEvent>;

export interface EndowmentWithdrawEventObject {
  endowId: BigNumber;
  tokenAddress: string;
  amount: BigNumber;
  accountType: number;
  beneficiaryAddress: string;
  beneficiaryEndowId: number;
}
export type EndowmentWithdrawEvent = TypedEvent<
  [BigNumber, string, BigNumber, number, string, number],
  EndowmentWithdrawEventObject
>;

export type EndowmentWithdrawEventFilter =
  TypedEventFilter<EndowmentWithdrawEvent>;

export interface OwnerUpdatedEventObject {
  owner: string;
}
export type OwnerUpdatedEvent = TypedEvent<[string], OwnerUpdatedEventObject>;

export type OwnerUpdatedEventFilter = TypedEventFilter<OwnerUpdatedEvent>;

export interface RefundNeededEventObject {
  arg0: IVault.VaultActionDataStructOutput;
}
export type RefundNeededEvent = TypedEvent<
  [IVault.VaultActionDataStructOutput],
  RefundNeededEventObject
>;

export type RefundNeededEventFilter = TypedEventFilter<RefundNeededEvent>;

export interface TokenSwappedEventObject {
  endowId: BigNumber;
  accountType: number;
  tokenIn: string;
  amountIn: BigNumber;
  tokenOut: string;
  amountOut: BigNumber;
}
export type TokenSwappedEvent = TypedEvent<
  [BigNumber, number, string, BigNumber, string, BigNumber],
  TokenSwappedEventObject
>;

export type TokenSwappedEventFilter = TypedEventFilter<TokenSwappedEvent>;

export interface UnexpectedTokensEventObject {
  arg0: IVault.VaultActionDataStructOutput;
}
export type UnexpectedTokensEvent = TypedEvent<
  [IVault.VaultActionDataStructOutput],
  UnexpectedTokensEventObject
>;

export type UnexpectedTokensEventFilter =
  TypedEventFilter<UnexpectedTokensEvent>;

export interface IAccounts extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAccountsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addGas(
      id: BigNumberish,
      vault: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    closeEndowment(
      id: BigNumberish,
      beneficiary: LibAccounts.BeneficiaryStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    createDaoContract(
      createdaomessage: SubDaoMessages.InstantiateMsgStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    createEndowment(
      details: AccountMessages.CreateEndowmentRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositDonationMatchERC20(
      id: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositERC20(
      details: AccountMessages.DepositRequestStruct,
      tokenAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    depositMatic(
      details: AccountMessages.DepositRequestStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    manageAllowances(
      endowId: BigNumberish,
      spender: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    queryAllowance(
      endowId: BigNumberish,
      spender: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    queryConfig(
      overrides?: CallOverrides
    ): Promise<
      [AccountMessages.ConfigResponseStructOutput] & {
        config: AccountMessages.ConfigResponseStructOutput;
      }
    >;

    queryEndowmentDetails(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [AccountStorage.EndowmentStructOutput] & {
        endowment: AccountStorage.EndowmentStructOutput;
      }
    >;

    queryState(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [AccountMessages.StateResponseStructOutput] & {
        stateResponse: AccountMessages.StateResponseStructOutput;
      }
    >;

    queryTokenAmount(
      id: BigNumberish,
      accountType: BigNumberish,
      tokenaddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { tokenAmount: BigNumber }>;

    setupDao(
      id: BigNumberish,
      details: SubDaoLib.DaoSetupStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setupDonationMatch(
      id: BigNumberish,
      details: AccountMessages.DonationMatchStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    spendAllowance(
      endowId: BigNumberish,
      token: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    strategyInvest(
      id: BigNumberish,
      investRequest: AccountMessages.InvestRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    strategyRedeem(
      id: BigNumberish,
      redeemRequest: AccountMessages.RedeemRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    strategyRedeemAll(
      id: BigNumberish,
      redeemAllRequest: AccountMessages.RedeemAllRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    swapToken(
      id: BigNumberish,
      accountType: BigNumberish,
      tokenIn: string,
      amountIn: BigNumberish,
      tokenOut: string,
      slippage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    sweepForClosure(
      id: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    sweepForEndowment(
      id: BigNumberish,
      vault: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateAcceptedToken(
      endowId: BigNumberish,
      tokenAddr: string,
      priceFeedAddr: string,
      tokenStatus: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateConfig(
      newRegistrar: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateDelegate(
      id: BigNumberish,
      setting: BigNumberish,
      action: BigNumberish,
      delegateAddress: string,
      delegateExpiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateEndowmentController(
      details: AccountMessages.UpdateEndowmentControllerRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateEndowmentDetails(
      details: AccountMessages.UpdateEndowmentDetailsRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateEndowmentSettings(
      details: AccountMessages.UpdateEndowmentSettingsRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateFeeSettings(
      details: AccountMessages.UpdateFeeSettingRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdraw(
      id: BigNumberish,
      acctType: BigNumberish,
      beneficiaryAddress: string,
      beneficiaryEndowId: BigNumberish,
      tokens: IAccountsDepositWithdrawEndowments.TokenInfoStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawDonationMatchERC20(
      id: BigNumberish,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  addGas(
    id: BigNumberish,
    vault: BigNumberish,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  closeEndowment(
    id: BigNumberish,
    beneficiary: LibAccounts.BeneficiaryStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  createDaoContract(
    createdaomessage: SubDaoMessages.InstantiateMsgStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  createEndowment(
    details: AccountMessages.CreateEndowmentRequestStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositDonationMatchERC20(
    id: BigNumberish,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositERC20(
    details: AccountMessages.DepositRequestStruct,
    tokenAddress: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  depositMatic(
    details: AccountMessages.DepositRequestStruct,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  manageAllowances(
    endowId: BigNumberish,
    spender: string,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  queryAllowance(
    endowId: BigNumberish,
    spender: string,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  queryConfig(
    overrides?: CallOverrides
  ): Promise<AccountMessages.ConfigResponseStructOutput>;

  queryEndowmentDetails(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<AccountStorage.EndowmentStructOutput>;

  queryState(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<AccountMessages.StateResponseStructOutput>;

  queryTokenAmount(
    id: BigNumberish,
    accountType: BigNumberish,
    tokenaddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setupDao(
    id: BigNumberish,
    details: SubDaoLib.DaoSetupStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setupDonationMatch(
    id: BigNumberish,
    details: AccountMessages.DonationMatchStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  spendAllowance(
    endowId: BigNumberish,
    token: string,
    amount: BigNumberish,
    recipient: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  strategyInvest(
    id: BigNumberish,
    investRequest: AccountMessages.InvestRequestStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  strategyRedeem(
    id: BigNumberish,
    redeemRequest: AccountMessages.RedeemRequestStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  strategyRedeemAll(
    id: BigNumberish,
    redeemAllRequest: AccountMessages.RedeemAllRequestStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  swapToken(
    id: BigNumberish,
    accountType: BigNumberish,
    tokenIn: string,
    amountIn: BigNumberish,
    tokenOut: string,
    slippage: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  sweepForClosure(
    id: BigNumberish,
    token: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  sweepForEndowment(
    id: BigNumberish,
    vault: BigNumberish,
    token: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateAcceptedToken(
    endowId: BigNumberish,
    tokenAddr: string,
    priceFeedAddr: string,
    tokenStatus: boolean,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateConfig(
    newRegistrar: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateDelegate(
    id: BigNumberish,
    setting: BigNumberish,
    action: BigNumberish,
    delegateAddress: string,
    delegateExpiry: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateEndowmentController(
    details: AccountMessages.UpdateEndowmentControllerRequestStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateEndowmentDetails(
    details: AccountMessages.UpdateEndowmentDetailsRequestStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateEndowmentSettings(
    details: AccountMessages.UpdateEndowmentSettingsRequestStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateFeeSettings(
    details: AccountMessages.UpdateFeeSettingRequestStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateOwner(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdraw(
    id: BigNumberish,
    acctType: BigNumberish,
    beneficiaryAddress: string,
    beneficiaryEndowId: BigNumberish,
    tokens: IAccountsDepositWithdrawEndowments.TokenInfoStruct[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawDonationMatchERC20(
    id: BigNumberish,
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    addGas(
      id: BigNumberish,
      vault: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    closeEndowment(
      id: BigNumberish,
      beneficiary: LibAccounts.BeneficiaryStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    createDaoContract(
      createdaomessage: SubDaoMessages.InstantiateMsgStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    createEndowment(
      details: AccountMessages.CreateEndowmentRequestStruct,
      overrides?: CallOverrides
    ): Promise<number>;

    depositDonationMatchERC20(
      id: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    depositERC20(
      details: AccountMessages.DepositRequestStruct,
      tokenAddress: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    depositMatic(
      details: AccountMessages.DepositRequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    manageAllowances(
      endowId: BigNumberish,
      spender: string,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    queryAllowance(
      endowId: BigNumberish,
      spender: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queryConfig(
      overrides?: CallOverrides
    ): Promise<AccountMessages.ConfigResponseStructOutput>;

    queryEndowmentDetails(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<AccountStorage.EndowmentStructOutput>;

    queryState(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<AccountMessages.StateResponseStructOutput>;

    queryTokenAmount(
      id: BigNumberish,
      accountType: BigNumberish,
      tokenaddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setupDao(
      id: BigNumberish,
      details: SubDaoLib.DaoSetupStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setupDonationMatch(
      id: BigNumberish,
      details: AccountMessages.DonationMatchStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    spendAllowance(
      endowId: BigNumberish,
      token: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    strategyInvest(
      id: BigNumberish,
      investRequest: AccountMessages.InvestRequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    strategyRedeem(
      id: BigNumberish,
      redeemRequest: AccountMessages.RedeemRequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    strategyRedeemAll(
      id: BigNumberish,
      redeemAllRequest: AccountMessages.RedeemAllRequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    swapToken(
      id: BigNumberish,
      accountType: BigNumberish,
      tokenIn: string,
      amountIn: BigNumberish,
      tokenOut: string,
      slippage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    sweepForClosure(
      id: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sweepForEndowment(
      id: BigNumberish,
      vault: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateAcceptedToken(
      endowId: BigNumberish,
      tokenAddr: string,
      priceFeedAddr: string,
      tokenStatus: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    updateConfig(
      newRegistrar: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateDelegate(
      id: BigNumberish,
      setting: BigNumberish,
      action: BigNumberish,
      delegateAddress: string,
      delegateExpiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateEndowmentController(
      details: AccountMessages.UpdateEndowmentControllerRequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    updateEndowmentDetails(
      details: AccountMessages.UpdateEndowmentDetailsRequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    updateEndowmentSettings(
      details: AccountMessages.UpdateEndowmentSettingsRequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFeeSettings(
      details: AccountMessages.UpdateFeeSettingRequestStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    updateOwner(newOwner: string, overrides?: CallOverrides): Promise<void>;

    withdraw(
      id: BigNumberish,
      acctType: BigNumberish,
      beneficiaryAddress: string,
      beneficiaryEndowId: BigNumberish,
      tokens: IAccountsDepositWithdrawEndowments.TokenInfoStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawDonationMatchERC20(
      id: BigNumberish,
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AllowanceSpent(uint256,address,address,uint256)"(
      endowId?: null,
      spender?: null,
      tokenAddress?: null,
      amount?: null
    ): AllowanceSpentEventFilter;
    AllowanceSpent(
      endowId?: null,
      spender?: null,
      tokenAddress?: null,
      amount?: null
    ): AllowanceSpentEventFilter;

    "AllowanceUpdated(uint256,address,address,uint256,uint256,uint256)"(
      endowId?: null,
      spender?: null,
      tokenAddress?: null,
      newBalance?: null,
      added?: null,
      deducted?: null
    ): AllowanceUpdatedEventFilter;
    AllowanceUpdated(
      endowId?: null,
      spender?: null,
      tokenAddress?: null,
      newBalance?: null,
      added?: null,
      deducted?: null
    ): AllowanceUpdatedEventFilter;

    "ConfigUpdated()"(): ConfigUpdatedEventFilter;
    ConfigUpdated(): ConfigUpdatedEventFilter;

    "DaoContractCreated(uint32,address)"(
      endowId?: null,
      daoAddress?: null
    ): DaoContractCreatedEventFilter;
    DaoContractCreated(
      endowId?: null,
      daoAddress?: null
    ): DaoContractCreatedEventFilter;

    "DonationDeposited(uint256,address,uint256)"(
      endowId?: null,
      tokenAddress?: null,
      amount?: null
    ): DonationDepositedEventFilter;
    DonationDeposited(
      endowId?: null,
      tokenAddress?: null,
      amount?: null
    ): DonationDepositedEventFilter;

    "DonationMatchCreated(uint256,address)"(
      endowId?: null,
      donationMatchContract?: null
    ): DonationMatchCreatedEventFilter;
    DonationMatchCreated(
      endowId?: null,
      donationMatchContract?: null
    ): DonationMatchCreatedEventFilter;

    "DonationWithdrawn(uint256,address,address,uint256)"(
      endowId?: null,
      recipient?: null,
      tokenAddress?: null,
      amount?: null
    ): DonationWithdrawnEventFilter;
    DonationWithdrawn(
      endowId?: null,
      recipient?: null,
      tokenAddress?: null,
      amount?: null
    ): DonationWithdrawnEventFilter;

    "EndowmentClosed(uint256)"(endowId?: null): EndowmentClosedEventFilter;
    EndowmentClosed(endowId?: null): EndowmentClosedEventFilter;

    "EndowmentCreated(uint256,uint8)"(
      endowId?: null,
      endowType?: null
    ): EndowmentCreatedEventFilter;
    EndowmentCreated(
      endowId?: null,
      endowType?: null
    ): EndowmentCreatedEventFilter;

    "EndowmentDeposit(uint256,address,uint256,uint256)"(
      endowId?: null,
      tokenAddress?: null,
      amountLocked?: null,
      amountLiquid?: null
    ): EndowmentDepositEventFilter;
    EndowmentDeposit(
      endowId?: null,
      tokenAddress?: null,
      amountLocked?: null,
      amountLiquid?: null
    ): EndowmentDepositEventFilter;

    "EndowmentInvested(uint8)"(arg0?: null): EndowmentInvestedEventFilter;
    EndowmentInvested(arg0?: null): EndowmentInvestedEventFilter;

    "EndowmentRedeemed(uint8)"(arg0?: null): EndowmentRedeemedEventFilter;
    EndowmentRedeemed(arg0?: null): EndowmentRedeemedEventFilter;

    "EndowmentSettingUpdated(uint256,string)"(
      endowId?: null,
      setting?: null
    ): EndowmentSettingUpdatedEventFilter;
    EndowmentSettingUpdated(
      endowId?: null,
      setting?: null
    ): EndowmentSettingUpdatedEventFilter;

    "EndowmentUpdated(uint256)"(endowId?: null): EndowmentUpdatedEventFilter;
    EndowmentUpdated(endowId?: null): EndowmentUpdatedEventFilter;

    "EndowmentWithdraw(uint256,address,uint256,uint8,address,uint32)"(
      endowId?: null,
      tokenAddress?: null,
      amount?: null,
      accountType?: null,
      beneficiaryAddress?: null,
      beneficiaryEndowId?: null
    ): EndowmentWithdrawEventFilter;
    EndowmentWithdraw(
      endowId?: null,
      tokenAddress?: null,
      amount?: null,
      accountType?: null,
      beneficiaryAddress?: null,
      beneficiaryEndowId?: null
    ): EndowmentWithdrawEventFilter;

    "OwnerUpdated(address)"(owner?: null): OwnerUpdatedEventFilter;
    OwnerUpdated(owner?: null): OwnerUpdatedEventFilter;

    "RefundNeeded((string,bytes4,bytes4,uint32[],address,uint256,uint256,uint8))"(
      arg0?: null
    ): RefundNeededEventFilter;
    RefundNeeded(arg0?: null): RefundNeededEventFilter;

    "TokenSwapped(uint256,uint8,address,uint256,address,uint256)"(
      endowId?: null,
      accountType?: null,
      tokenIn?: null,
      amountIn?: null,
      tokenOut?: null,
      amountOut?: null
    ): TokenSwappedEventFilter;
    TokenSwapped(
      endowId?: null,
      accountType?: null,
      tokenIn?: null,
      amountIn?: null,
      tokenOut?: null,
      amountOut?: null
    ): TokenSwappedEventFilter;

    "UnexpectedTokens((string,bytes4,bytes4,uint32[],address,uint256,uint256,uint8))"(
      arg0?: null
    ): UnexpectedTokensEventFilter;
    UnexpectedTokens(arg0?: null): UnexpectedTokensEventFilter;
  };

  estimateGas: {
    addGas(
      id: BigNumberish,
      vault: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    closeEndowment(
      id: BigNumberish,
      beneficiary: LibAccounts.BeneficiaryStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    createDaoContract(
      createdaomessage: SubDaoMessages.InstantiateMsgStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    createEndowment(
      details: AccountMessages.CreateEndowmentRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    depositDonationMatchERC20(
      id: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    depositERC20(
      details: AccountMessages.DepositRequestStruct,
      tokenAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    depositMatic(
      details: AccountMessages.DepositRequestStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    manageAllowances(
      endowId: BigNumberish,
      spender: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    queryAllowance(
      endowId: BigNumberish,
      spender: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queryConfig(overrides?: CallOverrides): Promise<BigNumber>;

    queryEndowmentDetails(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queryState(id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    queryTokenAmount(
      id: BigNumberish,
      accountType: BigNumberish,
      tokenaddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setupDao(
      id: BigNumberish,
      details: SubDaoLib.DaoSetupStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setupDonationMatch(
      id: BigNumberish,
      details: AccountMessages.DonationMatchStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    spendAllowance(
      endowId: BigNumberish,
      token: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    strategyInvest(
      id: BigNumberish,
      investRequest: AccountMessages.InvestRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    strategyRedeem(
      id: BigNumberish,
      redeemRequest: AccountMessages.RedeemRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    strategyRedeemAll(
      id: BigNumberish,
      redeemAllRequest: AccountMessages.RedeemAllRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    swapToken(
      id: BigNumberish,
      accountType: BigNumberish,
      tokenIn: string,
      amountIn: BigNumberish,
      tokenOut: string,
      slippage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    sweepForClosure(
      id: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    sweepForEndowment(
      id: BigNumberish,
      vault: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateAcceptedToken(
      endowId: BigNumberish,
      tokenAddr: string,
      priceFeedAddr: string,
      tokenStatus: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateConfig(
      newRegistrar: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateDelegate(
      id: BigNumberish,
      setting: BigNumberish,
      action: BigNumberish,
      delegateAddress: string,
      delegateExpiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateEndowmentController(
      details: AccountMessages.UpdateEndowmentControllerRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateEndowmentDetails(
      details: AccountMessages.UpdateEndowmentDetailsRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateEndowmentSettings(
      details: AccountMessages.UpdateEndowmentSettingsRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateFeeSettings(
      details: AccountMessages.UpdateFeeSettingRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdraw(
      id: BigNumberish,
      acctType: BigNumberish,
      beneficiaryAddress: string,
      beneficiaryEndowId: BigNumberish,
      tokens: IAccountsDepositWithdrawEndowments.TokenInfoStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawDonationMatchERC20(
      id: BigNumberish,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addGas(
      id: BigNumberish,
      vault: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    closeEndowment(
      id: BigNumberish,
      beneficiary: LibAccounts.BeneficiaryStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    createDaoContract(
      createdaomessage: SubDaoMessages.InstantiateMsgStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    createEndowment(
      details: AccountMessages.CreateEndowmentRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositDonationMatchERC20(
      id: BigNumberish,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositERC20(
      details: AccountMessages.DepositRequestStruct,
      tokenAddress: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    depositMatic(
      details: AccountMessages.DepositRequestStruct,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    manageAllowances(
      endowId: BigNumberish,
      spender: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    queryAllowance(
      endowId: BigNumberish,
      spender: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queryConfig(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    queryEndowmentDetails(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queryState(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queryTokenAmount(
      id: BigNumberish,
      accountType: BigNumberish,
      tokenaddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setupDao(
      id: BigNumberish,
      details: SubDaoLib.DaoSetupStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setupDonationMatch(
      id: BigNumberish,
      details: AccountMessages.DonationMatchStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    spendAllowance(
      endowId: BigNumberish,
      token: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    strategyInvest(
      id: BigNumberish,
      investRequest: AccountMessages.InvestRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    strategyRedeem(
      id: BigNumberish,
      redeemRequest: AccountMessages.RedeemRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    strategyRedeemAll(
      id: BigNumberish,
      redeemAllRequest: AccountMessages.RedeemAllRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    swapToken(
      id: BigNumberish,
      accountType: BigNumberish,
      tokenIn: string,
      amountIn: BigNumberish,
      tokenOut: string,
      slippage: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    sweepForClosure(
      id: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    sweepForEndowment(
      id: BigNumberish,
      vault: BigNumberish,
      token: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateAcceptedToken(
      endowId: BigNumberish,
      tokenAddr: string,
      priceFeedAddr: string,
      tokenStatus: boolean,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateConfig(
      newRegistrar: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateDelegate(
      id: BigNumberish,
      setting: BigNumberish,
      action: BigNumberish,
      delegateAddress: string,
      delegateExpiry: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateEndowmentController(
      details: AccountMessages.UpdateEndowmentControllerRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateEndowmentDetails(
      details: AccountMessages.UpdateEndowmentDetailsRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateEndowmentSettings(
      details: AccountMessages.UpdateEndowmentSettingsRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateFeeSettings(
      details: AccountMessages.UpdateFeeSettingRequestStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdraw(
      id: BigNumberish,
      acctType: BigNumberish,
      beneficiaryAddress: string,
      beneficiaryEndowId: BigNumberish,
      tokens: IAccountsDepositWithdrawEndowments.TokenInfoStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawDonationMatchERC20(
      id: BigNumberish,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
