name: JavaScript
on:
  push:
jobs:
  lint-tests:
    name: "Lint and test the codebase"
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.0"
      - name: Install dependencies
        run: bun run install
      - name: Lint codebase
        run: bun run lint
      - name: Test codebase
        run: bun run test --watchAll=false --coverage --json --outputFile ./codecov-report.json
        env:
          REACT_APP_JUNO_LCD_NODE: ${{ secrets.REACT_APP_JUNO_LCD_NODE }}
      - name: Build codebase
        run: bun run build
        env:
          REACT_APP_JUNO_LCD_NODE: ${{ secrets.REACT_APP_JUNO_LCD_NODE }}
