name: CI

on:
  push:

jobs:
  main:
    name: Nx Cloud - Main Job
    env:
      NX_JUNO_LCD_NODE: ${{ secrets.REACT_APP_JUNO_LCD_NODE }}
      NX_INFURA_ID: ${{ secrets.REACT_APP_INFURA_ID }}
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.3
    with:
      number-of-agents: 3
      init-commands: |
        yarn exec nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        yarn exec nx-cloud record -- yarn exec nx format:check
      parallel-commands-on-agents: |
        yarn exec nx affected --target=lint --parallel=3
        yarn exec nx affected --target=test --parallel=3 --ci --code-coverage
        yarn exec nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.3
    with:
      number-of-agents: 3
