name: JavaScript
on:
  push:
jobs:
  main:
    name: "Lint, test and build affected"
    permissions:
      contents: "read"
      actions: "read"

    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine head and base
        uses: nrwl/nx-set-shas@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Check format
        run: yarn nx format:check

      - name: Lint affected
        run: yarn nx affected:lint --parallel=3

      - name: Test affected
        run: yarn nx affected:test --parallel=3 --coverage
        env:
          NX_JUNO_LCD_NODE: ${{ secrets.REACT_APP_JUNO_LCD_NODE }}
          NX_INFURA_ID: ${{ secrets.REACT_APP_INFURA_ID }}

      - name: Build affected
        run: yarn nx affected:build --parallel=3

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
