name: JavaScript
on:
  push:
    branches:
  pull_request:
    branches:
jobs:
  lint:
    name: "Lint codebase"
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Lint codebase
        run: yarn run lint        
  test:
    name: "Test codebase"
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Test codebase
        run: yarn run test --watchAll=false --coverage
        env:
          REACT_APP_JUNO_LCD_NODE: ${{ secrets.REACT_APP_JUNO_LCD_NODE }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
