name: JavaScript
on:
  push:
jobs:
  lint-tests:
    name: "Lint and test the codebase"
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Lint codebase
        run: yarn lint
      - name: Test codebase
        run: yarn test --bail=0 --watch=false --passWithNoTests
      - name: Build codebase
        run: yarn build
