name: JavaScript
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_AMPLIFY_APP_ID: ${{ secrets.AWS_AMPLIFY_APP_ID }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: ./scripts/amplify-deploy.sh $AWS_AMPLIFY_APP_ID ${GITHUB_REF##*/}

  lint-tests:
    name: "Lint and test the codebase"
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Lint codebase
        run: yarn run lint
      - name: Test codebase
        run: yarn run test --watchAll=false --coverage --json --outputFile ./codecov-report.json
        env:
          REACT_APP_JUNO_LCD_NODE: ${{ secrets.REACT_APP_JUNO_LCD_NODE }}
      - name: Build codebase
        run: yarn build
        env:
          REACT_APP_JUNO_LCD_NODE: ${{ secrets.REACT_APP_JUNO_LCD_NODE }}
