name: JavaScript
on:
  push:
jobs:
  lint-tests:
    name: "Lint and test the codebase"
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Lint codebase
        run: yarn run lint
      - name: Test codebase
        run: yarn run test --watchAll=false --coverage --json --outputFile ./codecov-report.json
        env:
          REACT_APP_JUNO_LCD_NODE: ${{ secrets.REACT_APP_JUNO_LCD_NODE }}
          REACT_APP_INFURA_ID: ${{ secrets.REACT_APP_INFURA_ID }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
