name: JavaScript

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: "Lint codebase"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Lint codebase
        run: yarn run lint
        
  test:
    name: "Test codebase"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Test codebase
        run: yarn run test
        env:
          REACT_APP_FLEEK_API_KEY: 8piLIWpjQGTXfcaqWj1Uyg==
          REACT_APP_FLEEK_API_SECRET: bo+5ue2U9bCPYLcTBy83Bjp6tjsIzZDthl4FUvSu4hg=